### ISSUE TITLE
Search do not work

### ISSUE THREAD

**Issue by mostafaHamed** [shopizer-ecommerce/shopizer#133]
I have tried to search on a product but i got the following exception:

ERROR: com.shopizer.search.services.impl.SearchDelegateImpl - 
An error occured while searching {"root_cause":[{"type":"index_not_found_exception","reason":"no such index",
                                  "resource.type":"index_or_alias","resource.id":"keyword_en_default","index_uuid":"_na_","index":"keyword_en_default"}],
								  "type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"keyword_en_default",
								  "index_uuid":"_na_","index":"keyword_en_default"}

ERROR: com.shopizer.search.services.impl.SearchDelegateImpl - An error occured while searching {"root_cause":[{"type":"index_not_found_exception","reason":"no such inde
x","resource.type":"index_or_alias","resource.id":"keyword_en_default","index_uuid":"_na_","index":"keyword_en_default"}],"type":"index_not_found_exception","reason":"n
o such index","resource.type":"index_or_alias","resource.id":"keyword_en_default","index_uuid":"_na_","index":"keyword_en_default"}

ERROR: com.shopizer.search.services.impl.SearchDelegateImpl - An error occured while searching {"root_cause":[{"type":"index_not_found_exception","reason":"no such inde
x","resource.type":"index_or_alias","resource.id":"keyword_en_default","index_uuid":"_na_","index":"keyword_en_default"}],"type":"index_not_found_exception","reason":"n
o such index","resource.type":"index_or_alias","resource.id":"keyword_en_default","index_uuid":"_na_","index":"keyword_en_default"}
2017-02-04 00:51:53.358 ERROR 7668 --- [nio-8080-exec-6] c.s.c.b.s.search.SearchServiceImpl       : Error while searching keywords {"query":{"match":{"keyword":{"analyz
er":"standard","query":"no"}}}}

java.lang.NullPointerException: null
        at com.shopizer.search.services.worker.KeywordSearchWorkerImpl.execute(KeywordSearchWorkerImpl.java:24) ~[sm-search-2.0.5-SNAPSHOT.jar:2.0.5-SNAPSHOT]
        at com.shopizer.search.services.workflow.SearchWorkflow.searchAutocomplete(SearchWorkflow.java:48) ~[sm-search-2.0.5-SNAPSHOT.jar:2.0.5-SNAPSHOT]
        at com.shopizer.search.services.SearchService.searchAutoComplete(SearchService.java:91) ~[sm-search-2.0.5-SNAPSHOT.jar:2.0.5-SNAPSHOT]
        at com.salesmanager.core.business.services.search.SearchServiceImpl.searchForKeywords(SearchServiceImpl.java:182) ~[sm-core-2.0.5-SNAPSHOT.jar:2.0.5-SNAPSHOT]
        at com.salesmanager.shop.store.controller.search.SearchController.autocomplete(SearchController.java:116) [classes/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]

**Comment by aborigene** [comment]
I have the same problem, did you find a solution to this?
