### ISSUE TITLE
failed to upload images or files ,what's the problem?

### ISSUE THREAD

**Issue by tonywong2001** [shopizer-ecommerce/shopizer#155]
Log.
com.salesmanager.core.business.exception.ServiceException at com.salesmanager.core.business.modules.cms.content.infinispan.CmsStaticContentFileManagerImpl.addFiles(CmsStaticContentFileManagerImpl.java:146) at com.salesmanager.core.business.modules.cms.content.StaticContentFileManagerImpl.addFiles(StaticContentFileManagerImpl.java:49) at com.salesmanager.core.business.services.content.ContentServiceImpl.addContentFiles(ContentServiceImpl.java:272) at 

code:

 @Override
    public void addFiles( final String merchantStoreCode, final List<InputContentFile> inputStaticContentDataList )
        throws ServiceException
    {
        if ( cacheManager.getTreeCache() == null )
        {
            LOGGER.error( "Unable to find cacheManager.getTreeCache() in Infinispan.." );
            throw new ServiceException( "CmsStaticContentFileManagerInfinispanImpl has a null cacheManager.getTreeCache()" );
        }

**Comment by paulParis** [comment]
Hello,

There is a problem with jre1.8.xx

Take the lastest JDK or JRE 1.8_80++
