### ISSUE TITLE
Templates Error on Startup

### ISSUE THREAD

**Issue by syamsathyan** [shopizer-ecommerce/shopizer#159]
ResourceHttpRequestHandler]
2017-06-23 16:33:17.101 DEBUG 49541 --- [           main] o.s.w.s.v.f.FreeMarkerConfigurer         : Cannot resolve template loader path [classpath:/templates/] to [java.io.File]: using SpringTemplateLoader as fallback

java.io.FileNotFoundException: class path resource [templates/] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/Users/sathyans/.m2/repository/com/shopizer/sm-core/2.0.5-SNAPSHOT/sm-core-2.0.5-SNAPSHOT.jar!/templates/
	at org.springframework.util.ResourceUtils.getFile(ResourceUtils.java:218) ~[spring-core-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.core.io.AbstractFileResolvingResource.getFile(AbstractFileResolvingResource.java:52) ~[spring-core-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.ui.freemarker.FreeMarkerConfigurationFactory.getTemplateLoaderForPath(FreeMarkerConfigurationFactory.java:342) [spring-context-support-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.ui.freemarker.FreeMarkerConfigurationFactory.createConfiguration(FreeMarkerConfigurationFactory.java:290) [spring-context-support-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.web.servlet.view.freemarker.FreeMarkerConfigurer.afterPropertiesSet(FreeMarkerConfigurer.java:116) [spring-webmvc-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637) [spring-beans-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574) [spring-beans-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545) [spring-beans-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) [spring-beans-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) [spring-beans-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) [spring-beans-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) [spring-beans-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) [spring-beans-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772) [spring-beans-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839) [spring-context-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538) [spring-context-4.2.6.RELEASE.jar:4.2.6.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) [spring-boot-1.3.5.RELEASE.jar:1.3.5.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766) [spring-boot-1.3.5.RELEASE.jar:1.3.5.RELEASE]
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361) [spring-boot-1.3.5.RELEASE.jar:1.3.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) [spring-boot-1.3.5.RELEASE.jar:1.3.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1191) [spring-boot-1.3.5.RELEASE.jar:1.3.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1180) [spring-boot-1.3.5.RELEASE.jar:1.3.5.RELEASE]
	at com.salesmanager.shop.application.ShopApplication.main(ShopApplication.java:11) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_73]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_73]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_73]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_73]
	at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:478) [spring-boot-maven-plugin-1.3.5.RELEASE.jar:1.3.5.RELEASE]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_73]

2017-06-23 16:33:17.102  INFO 49541 --- [           main] o.s.ui.freemarker.SpringTemplateLoader   : SpringTemplateLoader for FreeMarker: using resource loader [org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@61b6acb3: startup date [Fri Jun 23 16:33:01 EDT 2017]; root of context hierarchy] and template loader path [classpath:/templates/]
2017-06-23 16:33:17.103  INFO 49541 --- [           main] o.s.w.s.v.f.FreeMarkerConfigurer         : ClassTemplateLoader for Spring macros added to FreeMarker configuration
2017-06-23 16:33:17.227  INFO 49541 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2017-06-23 16:33:17.247 DEBUG 49541 --- [           main] o.s.w.s.resource.ResourceUrlProvider     : Looking for resource handler mappings
2017-06-23 16:33:17.249 DEBUG 49541 --- [           main] o.s.w.s.resource.ResourceUrlProvider     : Found resource handler mapping: URL pattern="/**/favicon.ico", locations=[ServletContext resource [/], class path resource [META-INF/resources/], class path resource [resources/], class path resource [static/], class path resource [public/], class path resource []], resolvers=[org.springframework.web.servlet.resource.PathResourceResolver@64981abc]

JRE: java version "1.8.0_73"

**Comment by umeshawasthi** [comment]
Can you please let us know what all steps you are performing ?

**Comment by syamsathyan** [comment]
#Cloned: 2.0.5-SNAPSHOT
$cd shopizer
$mvn clean install
$cd sm-shop
$mvn spring-boot:run
 
 
 
--Regards
  
 Syam Sathyan George
 (My Boss is a Jewish Carpenter)
 
 HEAD OF SYSTEMS & ENGINEERING
Vuoto-Labs
 Atlanta, GA
 cell: 1-404-662-6518
off : 1-404-400-2959
  
 
--------- Original Message --------- Subject: Re: [shopizer-ecommerce/shopizer] Templates Error on Startup (#159)

**Comment by syamsathyan** [comment]
Umesh,
 
PFA, Complete Log attached ....
 
 
--Regards
  
 Syam Sathyan George
 (My Boss is a Jewish Carpenter)
 
 HEAD OF SYSTEMS & ENGINEERING
Vuoto-Labs
 Atlanta, GA
 cell: 1-404-662-6518
off : 1-404-400-2959
  
 
--------- Original Message --------- Subject: Re: [shopizer-ecommerce/shopizer] Templates Error on Startup (#159)

**Comment by umeshawasthi** [comment]
Hey @syamsathyan  : I have written a complete post on how to run Shopizer [build-and-run-shopizer](http://www.umeshawasthi.com/shopizer/build-and-run-shopizer/). Let me know if this still not working for you and I will try to retest it tonight, I might need following additional information from you

1. JDK version
2. Maven Version

**Comment by syamsathyan** [comment]
Apache Maven 3.5.0
java version "1.8.0_73"

**Comment by shopizer-ecommerce** [comment]
Since the migration to spring boot that situation occurs but the application runs and get the templates

**Comment by shopizer-ecommerce** [comment]
This message should not prevent starting the application, any error after this message is displayed ?
