### ISSUE TITLE
 Error during installing

### ISSUE THREAD

**Issue by shangwenqingqing** [shopizer-ecommerce/shopizer#166]
Caused by: java.lang.ClassNotFoundException: org.codehaus.plexus.compiler.util.scan.InclusionScanException
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
        ... 55 more
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] sm-core-model ...................................... FAILURE [ 29.923 s]
[INFO] sm-core-modules .................................... SKIPPED
[INFO] sm-search .......................................... SKIPPED
[INFO] shopizer-shipping-distance-processor ............... SKIPPED
[INFO] shopizer-shipping-canadapost-module ................ SKIPPED
[INFO] sm-core ............................................ SKIPPED
[INFO] sm-shop ............................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 30.366 s
[INFO] Finished at: 2017-08-25T15:12:49+08:00
[INFO] Final Memory: 27M/231M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project sm-core-model: Execution default-compile of goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile failed: A required class was missing while executing org.apache.maven.plugins:maven-compiler-plugin:3.1:compile: org/codehaus/plexus/compiler/util/scan/InclusionScanException

**Comment by shopizer-ecommerce** [comment]
Are you running the build from a command line ?

$ cd shopizer
$ mvn clean install

or from an IDEA ?
