### ISSUE TITLE
change tomcat port

### ISSUE THREAD

**Issue by Emma04** [shopizer-ecommerce/shopizer#217]
Hello everyone
If I want to change the port instead of 8080 I want to have 80
In which file I should edit?
I am using a virtual machine to host shopizer http://ipAdress:8080/shop but for some reason google analytic doesn't accept it and I have to edit to http://ipAdress/shop when the port is set to 80

Hope it is clear.
Plz I am counting on your help
Regards,

**Comment by umeshawasthi** [comment]
Edit your application.properties file under shop /resource folder and set the following property

server.port = 80

**Comment by Emma04** [comment]
Thank you very much

**Comment by Emma04** [comment]
in my localhost in works just fine
I did the same thing for my virtual machine in google compute engine (editing the file ad adding servert.port=80)and it fails and I had errors. 
Previously it was working just fine
PLZ help me!
A parts of the errors are there
[WARNING] 
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:478)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat servlet container
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletContainer.java:165)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:293)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:141)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766)
        at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1191)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1180)
        at com.salesmanager.shop.application.ShopApplication.main(ShopApplication.java:11)
        ... 6 more
Caused by: java.lang.IllegalStateException: Tomcat connector in failed state
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletContainer.java:159)
        ... 16 more

**Comment by Emma04** [comment]
Plz @umeshawasthi  I am counting on you

**Comment by umeshawasthi** [comment]
Can you share complete error log? Are you running embedded tomcat on Google VM as well?

**Comment by Emma04** [comment]
As you can see in errors.txt all the errors and in firewall rules, my configuration...
Seems everything is fine
[errors.txt](https://github.com/shopizer-ecommerce/shopizer/files/1945671/errors.txt)
![firewall rules](https://user-images.githubusercontent.com/17785779/39228807-e3a04fc8-489a-11e8-8881-f20c052c7af1.JPG)

**Comment by Emma04** [comment]
actually it works fine now
Even if the port 80 was enabled, it wasn't working on Ubuntu.
So if someone is facing the same issue I did the followed line and now it is working
sudo apt-get install authbind
sudo touch /etc/authbind/byport/80
sudo chmod 777 /etc/authbind/byport/80

and authbind --deep mvn spring-boot:run
