### ISSUE TITLE
A null pointer exception is thrown when removing an item from the cart

### ISSUE THREAD

**Issue by judef1** [shopizer-ecommerce/shopizer#248]
I get a null pointer exception when I try to remove an item from the cart that was added in the homepage (Storefront)
Steps to reproduce
1. Add the Retro Style Bag to the cart from the homepage
2. Scroll up and go to the checkout page
3. Click on the "X" to remove the item from the cart
Result: The user is redirected to null pointer exception page
Expected: The item should have been removed from the cart

Note: it looks like when the user add from the homepage the cart isn't created

**Comment by judef1** [comment]
Partial stack trace : 

java.lang.NullPointerException: Requires ShoppingCart at org.apache.commons.lang3.Validate.notNull(Validate.java:225) at com.salesmanager.shop.populator.shoppingCart.ShoppingCartDataPopulator.populate(ShoppingCartDataPopulator.java:90) at com.salesmanager.shop.populator.shoppingCart.ShoppingCartDataPopulator.populate(ShoppingCartDataPopulator.java:42) at com.salesmanager.core.business.utils.AbstractDataPopulator.populate(AbstractDataPopulator.java:34) at com.salesmanager.shop.store.controller.shoppingCart.facade.ShoppingCartFacadeImpl.removeCartItem(ShoppingCartFacadeImpl.java:491) at com.salesmanager.shop.store.controller.shoppingCart.ShoppingCartController.removeShoppingCartItem(ShoppingCartController.java:391)
