### ISSUE TITLE
"mvn spring-boot:run" The command failed to find the file.

### ISSUE THREAD

**Issue by t0rjan** [shopizer-ecommerce/shopizer#271]
```

2018-12-03 17:56:45.130  WARN 28990 --- [ost-startStop-1] o.a.tomcat.util.scan.StandardJarScanner  : Failed to scan [file:/Users/admin/.m2/repository/org/jopendocument/jOpenDocument/1.3/xbean.jar] from classloader hierarchy

java.io.FileNotFoundException: /Users/admin/.m2/repository/org/jopendocument/jOpenDocument/1.3/xbean.jar (No such file or directory)
	at java.util.zip.ZipFile.open(Native Method) ~[na:1.8.0_131]
	at java.util.zip.ZipFile.<init>(ZipFile.java:219) ~[na:1.8.0_131]
	at java.util.zip.ZipFile.<init>(ZipFile.java:149) ~[na:1.8.0_131]
	at java.util.jar.JarFile.<init>(JarFile.java:166) ~[na:1.8.0_131]
	at java.util.jar.JarFile.<init>(JarFile.java:130) ~[na:1.8.0_131]
	at org.apache.tomcat.util.scan.JarFileUrlJar.<init>(JarFileUrlJar.java:60) ~[tomcat-embed-core-8.5.14.jar:8.5.14]
	at org.apache.tomcat.util.scan.JarFactory.newInstance(JarFactory.java:49) ~[tomcat-embed-core-8.5.14.jar:8.5.14]
	at org.apache.tomcat.util.scan.StandardJarScanner.process(StandardJarScanner.java:338) ~[tomcat-embed-core-8.5.14.jar:8.5.14]
	at org.apache.tomcat.util.scan.StandardJarScanner.scan(StandardJarScanner.java:288) ~[tomcat-embed-core-8.5.14.jar:8.5.14]
	at org.apache.jasper.servlet.TldScanner.scanJars(TldScanner.java:262) [tomcat-embed-jasper-8.5.14.jar:8.5.14]
	at org.apache.jasper.servlet.TldScanner.scan(TldScanner.java:104) [tomcat-embed-jasper-8.5.14.jar:8.5.14]
	at org.apache.jasper.servlet.JasperInitializer.onStartup(JasperInitializer.java:101) [tomcat-embed-jasper-8.5.14.jar:8.5.14]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5196) [tomcat-embed-core-8.5.14.jar:8.5.14]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.5.14.jar:8.5.14]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419) [tomcat-embed-core-8.5.14.jar:8.5.14]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409) [tomcat-embed-core-8.5.14.jar:8.5.14]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]

2018-12-03 17:56:45.131  WARN 28990 --- [ost-startStop-1] o.a.tomcat.util.scan.StandardJarScanner  : Failed to scan [file:/Users/admin/.m2/repository/com/mchange/c3p0/0.9.5.2/mchange-commons-java-0.2.11.jar] from classloader hierarchy

java.io.FileNotFoundException: /Users/admin/.m2/repository/com/mchange/c3p0/0.9.5.2/mchange-commons-java-0.2.11.jar (No such file or directory)
	at java.util.zip.ZipFile.open(Native Method) ~[na:1.8.0_131]
	at java.util.zip.ZipFile.<init>(ZipFile.java:219) ~[na:1.8.0_131]
	at java.util.zip.ZipFile.<init>(ZipFile.java:149) ~[na:1.8.0_131]
	at java.util.jar.JarFile.<init>(JarFile.java:166) ~[na:1.8.0_131]
	at java.util.jar.JarFile.<init>(JarFile.java:130) ~[na:1.8.0_131]
	at org.apache.tomcat.util.scan.JarFileUrlJar.<init>(JarFileUrlJar.java:60) ~[tomcat-embed-core-8.5.14.jar:8.5.14]
	at org.apache.tomcat.util.scan.JarFactory.newInstance(JarFactory.java:49) ~[tomcat-embed-core-8.5.14.jar:8.5.14]
	at org.apache.tomcat.util.scan.StandardJarScanner.process(StandardJarScanner.java:338) ~[tomcat-embed-core-8.5.14.jar:8.5.14]
	at org.apache.tomcat.util.scan.StandardJarScanner.scan(StandardJarScanner.java:288) ~[tomcat-embed-core-8.5.14.jar:8.5.14]
	at org.apache.jasper.servlet.TldScanner.scanJars(TldScanner.java:262) [tomcat-embed-jasper-8.5.14.jar:8.5.14]
	at org.apache.jasper.servlet.TldScanner.scan(TldScanner.java:104) [tomcat-embed-jasper-8.5.14.jar:8.5.14]
	at org.apache.jasper.servlet.JasperInitializer.onStartup(JasperInitializer.java:101) [tomcat-embed-jasper-8.5.14.jar:8.5.14]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5196) [tomcat-embed-core-8.5.14.jar:8.5.14]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.5.14.jar:8.5.14]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419) [tomcat-embed-core-8.5.14.jar:8.5.14]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409) [tomcat-embed-core-8.5.14.jar:8.5.14]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]

2018-12-03 17:56:45.143  INFO 28990 --- [ost-startStop-1] org.apache.jasper.servlet.TldScanner     : At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
2018-12-03 17:56:45.151  INFO 28990 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2018-12-03 17:56:45.151  INFO 28990 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 5527 ms
2018-12-03 17:56:45.393  INFO 28990 --- [ost-startStop-1] o.s.s.web.DefaultSecurityFilterChain     : Creating filter chain: Ant [pattern='/resources/**'], []
2018-12-03 17:56:45.399  INFO 28990 --- [ost-startStop-1] o.s.s.web.DefaultSecurityFilterChain     : Creating filter chain: Ant [pattern='/layout/**'], []
2018-12-03 17:56:45.655  INFO 28990 --- [g-Init-Reporter] com.mchange.v2.log.MLog                  : MLog clients using slf4j logging.
2018-12-03 17:56:45.705  INFO 28990 --- [ost-startStop-1] com.mchange.v2.c3p0.C3P0Registry         : Initializing c3p0-0.9.5.2 [built 08-December-2015 22:06:04 -0800; debug? true; trace: 10]
2018-12-03 17:56:46.171  INFO 28990 --- [ost-startStop-1] j.LocalContainerEntityManagerFactoryBean : Building JPA container EntityManagerFactory for persistence unit 'default'
2018-12-03 17:56:46.194  INFO 28990 --- [ost-startStop-1] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [
	name: default
	...]

```

**Comment by shopizer-ecommerce** [comment]
That is unfortunately 'normal' since new tomcat package imspector. Those errors do not prevent running the application
