### ISSUE TITLE
Search Box does not work because of Elasticsearch error

### ISSUE THREAD

**Issue by hungtrquoc** [shopizer-ecommerce/shopizer#312]
Auto complete on search box but no items found when search.
Log on ElasticSearch server: (CentOS 7.5 x64, ElasticSearch 6.6.1)
org.elasticsearch.transport.RemoteTransportException: [XwA7Ljc][127.0.0.1:9300][indices:data/read/search[phase/query]]
Caused by: java.lang.IllegalArgumentException: Fielddata is disabled on text fields by default. Set fielddata=true on [categories] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.
        at org.elasticsearch.index.mapper.TextFieldMapper$TextFieldType.fielddataBuilder(TextFieldMapper.java:670) ~[elasticsearch-6.6.1.jar:6.6.1]
        at org.elasticsearch.index.fielddata.IndexFieldDataService.getForField(IndexFieldDataService.java:116) ~[elasticsearch-6.6.1.jar:6.6.1]
        at org.elasticsearch.index.query.QueryShardContext.getForField(QueryShardContext.java:166) ~[elasticsearch-6.6.1.jar:6.6.1]
        at org.elasticsearch.search.aggregations.support.ValuesSourceConfig.resolve(ValuesSourceConfig.java:95) ~[elasticsearch-6.6.1.jar:6.6.1]
        at org.elasticsearch.search.aggregations.support.ValuesSourceAggregationBuilder.resolveConfig(ValuesSourceAggregationBuilder.java:317) ~[elasticsearch-6.6.1.jar:6.6.1]
        at org.elasticsearch.search.aggregations.support.ValuesSourceAggregationBuilder.doBuild(ValuesSourceAggregationBuilder.java:310) ~[elasticsearch-6.6.1.jar:6.6.1]
        at org.elasticsearch.search.aggregations.support.ValuesSourceAggregationBuilder.doBuild(ValuesSourceAggregationBuilder.java:37) ~[elasticsearch-6.6.1.jar:6.6.1]
        at org.elasticsearch.search.aggregations.AbstractAggregationBuilder.build(AbstractAggregationBuilder.java:139) ~[elasticsearch-6.6.1.jar:6.6.1]
        at org.elasticsearch.search.aggregations.AggregatorFactories$Builder.build(AggregatorFactories.java:336) ~[elasticsearch-6.6.1.jar:6.6.1]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:848) ~[elasticsearch-6.6.1.jar:6.6.1]
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:656) ~[elasticsearch-6.6.1.jar:6.6.1]
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:631) ~[elasticsearch-6.6.1.jar:6.6.1]
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:388) ~[elasticsearch-6.6.1.jar:6.6.1]
        at org.elasticsearch.search.SearchService.access$100(SearchService.java:126) ~[elasticsearch-6.6.1.jar:6.6.1]
        at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:360) [elasticsearch-6.6.1.jar:6.6.1]
        at org.elasticsearch.search.SearchService$2.onResponse(SearchService.java:356) [elasticsearch-6.6.1.jar:6.6.1]
        at org.elasticsearch.search.SearchService$4.doRun(SearchService.java:1117) [elasticsearch-6.6.1.jar:6.6.1]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:759) [elasticsearch-6.6.1.jar:6.6.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.6.1.jar:6.6.1]
        at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:41) [elasticsearch-6.6.1.jar:6.6.1]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-6.6.1.jar:6.6.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]

**Comment by umeshawasthi** [comment]
Which Elastic search version you are using? You are using 6.6.1.Shopizer 2.3.0 support Elastic search version <=1.7.It looks like you are using

**Comment by carlsamson** [comment]
Elastic Search 5.X will work not 6.X

**Comment by shopizer-ecommerce** [comment]
Use ES 5.X, no support yet for ES 6.X

**Comment by hungtrquoc** [comment]
Still not woking with ES 5.6.9. ES ask to set Fielddata =true.
Caused by: java.lang.IllegalArgumentException: Fielddata is disabled on text fields by default. Set fielddata=true on [categories] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.
        at org.elasticsearch.index.mapper.TextFieldMapper$TextFieldType.fielddataBuilder(TextFieldMapper.java:336) ~[elasticsearch-5.6.9.jar:5.6.9]
        at org.elasticsearch.index.fielddata.IndexFieldDataService.getForField(IndexFieldDataService.java:111) ~[elasticsearch-5.6.9.jar:5.6.9]
        at org.elasticsearch.index.query.QueryShardContext.getForField(QueryShardContext.java:166) ~[elasticsearch-5.6.9.jar:5.6.9]
        at org.elasticsearch.search.aggregations.support.ValuesSourceConfig.resolve(ValuesSourceConfig.java:96) ~[elasticsearch-5.6.9.jar:5.6.9]
        at org.elasticsearch.search.aggregations.support.ValuesSourceAggregationBuilder.resolveConfig(ValuesSourceAggregationBuilder.java:297) ~[elasticsearch-5.6.9.jar:5.6.9]
        at org.elasticsearch.search.aggregations.support.ValuesSourceAggregationBuilder.doBuild(ValuesSourceAggregationBuilder.java:290) ~[elasticsearch-5.6.9.jar:5.6.9]
        at org.elasticsearch.search.aggregations.support.ValuesSourceAggregationBuilder.doBuild(ValuesSourceAggregationBuilder.java:39) ~[elasticsearch-5.6.9.jar:5.6.9]
        at org.elasticsearch.search.aggregations.AbstractAggregationBuilder.build(AbstractAggregationBuilder.java:126) ~[elasticsearch-5.6.9.jar:5.6.9]
        at org.elasticsearch.search.aggregations.AggregatorFactories$Builder.build(AggregatorFactories.java:347) ~[elasticsearch-5.6.9.jar:5.6.9]
        at org.elasticsearch.search.SearchService.parseSource(SearchService.java:655) ~[elasticsearch-5.6.9.jar:5.6.9]
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:485) ~[elasticsearch-5.6.9.jar:5.6.9]
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:461) ~[elasticsearch-5.6.9.jar:5.6.9]
        at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:257) ~[elasticsearch-5.6.9.jar:5.6.9]
        at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:343) ~[elasticsearch-5.6.9.jar:5.6.9]
        at org.elasticsearch.action.search.SearchTransportService$6.messageReceived(SearchTransportService.java:340) ~[elasticsearch-5.6.9.jar:5.6.9]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69) ~[elasticsearch-5.6.9.jar:5.6.9]
        at org.elasticsearch.transport.TransportService$7.doRun(TransportService.java:654) [elasticsearch-5.6.9.jar:5.6.9]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:674) [elasticsearch-5.6.9.jar:5.6.9]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-5.6.9.jar:5.6.9]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]

**Comment by hungtrquoc** [comment]
@shopizer-ecommerce @carlsamson pls reopen this case.

**Comment by carlsamson** [comment]
please post this file
sm-core/src/main/resources/search/product.json

**Comment by hungtrquoc** [comment]
{"product_en": {
						"properties" :  {
							"name": {"type": "text","fields": {"name_original":{"type":"keyword","index":"not_analyzed"},"name_searchable":{"type":"text","fielddata": true,"index":"analyzed","store":"no"}}},	
							"price" : {"type":"keyword","index":"not_analyzed"},
							"categories" : {"type":"keyword","index":"not_analyzed"},
							"lang" : {"type":"keyword","index":"not_analyzed"},
							"store" : {"type":"keyword","index":"not_analyzed"},
							"availability" : {"type":"keyword","index":"not_analyzed"},
							"available" : {"type":"keyword","index":"not_analyzed"},
							"description" : {"type":"text","fielddata": true,"index":"analyzed","analyzer": "english"}, 
							"tags" : {"type":"text","fielddata": true,"index":"analyzed"} 
						 } 
			}
}

**Comment by carlsamson** [comment]
Error says 
`Fielddata is disabled on **text** fields by default. Set fielddata=true on [categories] in order to load fielddata`

But your mapping is not text but keyword
"categories" : {"type":"**keyword**","index":"not_analyzed"},

start elastic search 5.X, once started open your browser
and type this url

http://<host>:9200/product_en/_settings,_mappings

Post results here

**Comment by hungtrquoc** [comment]
here is result:

{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"product_en","index_uuid":"_na_","index":"product_en"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"product_en","index_uuid":"_na_","index":"product_en"},"status":404}

**Comment by shopizer-ecommerce** [comment]
ok i see that for some reason index is not created.

Next step, 

stop elastic search and delete elasticsearch/data/shopizer directory and restart
have your elastic search console nearby so you can see activity
From shopizer open a product, click on save then look in elastic search console

- log elastic search error if any in that thread
- type this url again http://host:9200/product_en/_settings,_mappings and see if it still says ndex_not_found_exception
- retry to search in your search box

**Comment by hungtrquoc** [comment]
here is result:
{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"product_en","index_uuid":"_na_","index":"product_en"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"product_en","index_uuid":"_na_","index":"product_en"},"status":404}

**Comment by shopizer-ecommerce** [comment]
Post post shopizer log after the server was restarted
