### ISSUE TITLE
Problems to connect do mysql

### ISSUE THREAD

**Issue by dhiegopiroto** [shopizer-ecommerce/shopizer#349]
Hi,
I being facing problems to configure my shopizer with mysql. 
Apparently all is configured but I still receiving error messages saying "Unable to open JDBC connection for schema management target"
I know it seems quite simple: driver problems or wrong version... however it has the right one (unless Im missing something  :/  )
Does anyone have a idea what it could be?

Thanks for the attention 

**#Error Message in catalina.log**

```
SEVERE: ContainerBase.addChild: start: 
org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:162)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:899)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1092)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1984)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.beans.factory.BeanCreationException: 
Error creating bean with name 'org.springframework.security.filterChainProxy': Cannot resolve reference to bean 'org.springframework.security.filterChains' while setting constructor argument; 
nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.security.filterChains': Cannot resolve reference to bean 
'org.springframework.security.web.DefaultSecurityFilterChain#2' while setting bean property 'sourceList' with key [2]; nested exception is org.springframework.beans.factory.BeanCreationException: 
Error creating bean with name 'org.springframework.security.web.DefaultSecurityFilterChain#2': Cannot resolve reference to bean 'org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter#0'
 while setting constructor argument with key [4]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 
 'org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter#0': Cannot resolve reference to bean 'userAuthenticationSuccessHandler' 
 while setting bean property 'authenticationSuccessHandler'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 
 'userAuthenticationSuccessHandler': Unsatisfied dependency expressed through field 'userService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 
 'userService' defined in class path resource [spring/shopizer-core-config.xml]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: 
 Error creating bean with name 'userRepositoryImpl': Injection of persistence dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' 
 defined in class path resource [spring/shopizer-core-config.xml]: Invocation of init method failed; nested exception is javax.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate
  SessionFactory; 
nested exception is org.hibernate.tool.schema.spi.SchemaManagementException: Unable to open JDBC connection for schema management target
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:139)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:536)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:124)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.web.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:156)
	at org.springframework.boot.web.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:136)
	at org.springframework.boot.web.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:91)
	at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:169)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5623)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
```

**database.properties**

```
#MYSQL
db.jdbcUrl=jdbc:mysql://10.10.10.10:3306/SALESMANAGER?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
db.user=root
db.password=Passwd@123
db.driverClass=com.mysql.jdbc.Driver
#for mysql 8 - update driver to 8.X
#db.driverClass=com.mysql.cj.jdbc.Driver
hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
```

**#Telnet from App server to DB server**
```
[root@eCommerce tomcat]# telnet 110.10.10.10 3306
Trying 10.10.10.10...
Connected to 10.10.10.10
Escape character is '^]'.
J
5.6.44,]I6pT3B?mR2D@Ug)3d!smysql_native_passwordConnection closed by foreign host.


```
**

#Driver in the app server

**

```
> [root@eCommerce lib]# pwd
> /var/lib/tomcat/webapps/ROOT/WEB-INF/lib
> [root@eCommerce lib]# ls *mysql-connector-java*
> mysql-connector-java-5.1.47.jar
> 
```

**#shopizer/pom.xml**
```
        <properties>
                [...]
                <mysql-jdbc-version>5.1.47</mysql-jdbc-version>
                [...]
        </properties>
```

**#Accessing mySql vi cli from app server**
```
[root@eCommerce tomcat]# mysql -h 10.10.10.10 --port=3306 -u root -p
Enter password: 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MySQL connection id is 45
Server version: 5.6.44 MySQL Community Server (GPL)

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MySQL [(none)]> 

```

ps: the ip 10.10.10.10 is illustrative.

**Comment by bautrey37** [comment]
Any updates on this problem?

**Comment by shopizer-ecommerce** [comment]
All versions are aligned, it has to do with connectivity from client to server. Is app running on same host where your sql server is, 

have you tried to grant privileges from all ips

better not using root user, create specific user

GRANT ALL PRIVILEGES
ON SALESMANAGER
TO 'user'@'%'
IDENTIFIED BY 'newpassword';
