### ISSUE TITLE
Shop registration error

### ISSUE THREAD

**Issue by syshex** [shopizer-ecommerce/shopizer#416]
Going to the top Menu bar ,  My Account > Register   fails  opening : /shop/customer/registration.html

Branch : 2.11.0
Running using Spring Boot. 
DB is the H2 default db. 

```
2020-04-22 11:52:26.560  WARN 19380 --- [nio-8080-exec-4] o.h.h.internal.ast.QueryTranslatorImpl   : HHH000104: firstResult/maxResults specified with collection fetch; applying in memory!
2020-04-22 11:52:26.588 ERROR 19380 --- [nio-8080-exec-4] o.a.c.c.C.[.[localhost].[/].[jsp]        : Servlet.service() for servlet [jsp] threw exception

org.apache.jasper.JasperException: /pages/shop/templates/december/pages/register.jsp (line: [103], column: [8]) Unable to find setter method for attribute: [commandName]
	at org.apache.jasper.compiler.DefaultErrorHandler.jspError(DefaultErrorHandler.java:42) ~[tomcat-embed-jasper-9.0.31.jar:9.0.31]
	at org.apache.jasper.compiler.ErrorDispatcher.dispatch(ErrorDispatcher.java:292) ~[tomcat-embed-jasper-9.0.31.jar:9.0.31]
	at org.apache.jasper.compiler.ErrorDispatcher.jspError(ErrorDispatcher.java:115) ~[tomcat-embed-jasper-9.0.31.jar:9.0.31]
	at org.apache.jasper.compiler.Generator$GenerateVisitor.evaluateAttribute(Generator.java:3015) ~[tomcat-embed-jasper-9.0.31.jar:9.0.31]
	at org.apache.jasper.compiler.Generator$GenerateVisitor.generateSetters(Generator.java:3235) ~[tomcat-embed-jasper-9.0.31.jar:9.0.31]
	at org.apache.jasper.compiler.Generator$GenerateVisitor.generateCustomStart(Generator.java:2421) ~[tomcat-embed-jasper-9.0.31.jar:9.0.31]
	at org.apache.jasper.compiler.Generator$GenerateVisitor.visit(Generator.java:1911) ~[tomcat-embed-jasper-9.0.31.jar:9.0.31]
	at org.apache.jasper.compiler.Node$CustomTag.accept(Node.java:1544) ~[tomcat-embed-jasper-9.0.31.jar:9.0.31]
	at org.apache.jasper.compiler.Node$Nodes.visit(Node.java:2389) ~[tomcat-embed-jasper-9.0.31.jar:9.0.31]
	at org.apache.jasper.compiler.Node$Visitor.visitBody(Node.java:2441) ~[tomcat-embed-jasper-9.0.31.jar:9.0.31]
	at org.apache.jasper.compiler.Node$Visitor.visit(Node.java:2447) ~[tomcat-embed-jasper-9.0.31.jar:9.0.31]
	at org.apache.jasper.compiler.Node$Root.accept(Node.java:470) ~[tomcat-embed-jasper-9.0.31.jar:9.0.31]
	at org.apache.jasper.compiler.Node$Nodes.visit(Node.java:2389) ~[tomcat-embed-jasper-9.0.31.jar:9.0.31]
	at org.apache.jasper.compiler.Generator.generate(Generator.java:3676) ~[tomcat-embed-jasper-9.0.31.jar:9.0.31]
	at org.apache.jasper.compiler.Compiler.generateJava(Compiler.java:257) ~[tomcat-embed-jasper-9.0.31.jar:9.0.31]
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:386) ~[tomcat-embed-jasper-9.0.31.jar:9.0.31]
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:362) ~[tomcat-embed-jasper-9.0.31.jar:9.0.31]
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:346) ~[tomcat-embed-jasper-9.0.31.jar:9.0.31]

```

**Comment by shopizer-ecommerce** [comment]
commandName needs to be changed to modelAttribute. Following migration to Spring boot 2 this jsp was missed. Will be fixed shortly

**Comment by syshex** [comment]
want a PR ? or not worth it ?

**Comment by shopizer-ecommerce** [comment]
No thanks, it is about to be released

**Comment by shopizer-ecommerce** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Registration  not working in 2.11.0](https://trello.com/c/D8QFROWT/2-registration-not-working-in-2110)
