### ISSUE TITLE
Error while running shopizer using docker compose

### ISSUE THREAD

**Issue by Hassaballah101** [shopizer-ecommerce/shopizer#440]
I'm having an issue running shopizer using docker compose with all the dependencies as mentioned in the documentation, but i'm facing the below error:
Could u please have a look?

** running using linux- debian on AWS

shopizer       | 2020-06-24 21:39:11.882  WARN 1 --- [ost-startStop-1] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: 
org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'secretKey' defined in class path resource [spring/shopizer-core-config.xml]: Could not resolve pl
aceholder 'secretKey' in value "${secretKey}"; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'secretKey' in value "${secretKey}"
shopizer       | 2020-06-24 21:39:11.923  INFO 1 --- [ost-startStop-1] ConditionEvaluationReportLoggingListener : 
shopizer       | 
shopizer       | Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
shopizer       | 2020-06-24 21:39:11.939 ERROR 1 --- [ost-startStop-1] o.s.boot.SpringApplication               : Application run failed
shopizer       | 
shopizer       | org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'secretKey' defined in class path resource [spring/shopizer-core-config.xml]: Cou
ld not resolve placeholder 'secretKey' in value "${secretKey}"; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'secretKey' in value "${secretKey}"
shopizer       |        at org.springframework.beans.factory.config.PlaceholderConfigurerSupport.doProcessProperties(PlaceholderConfigurerSupport.java:228) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.R
ELEASE]
shopizer       |        at org.springframework.context.support.PropertySourcesPlaceholderConfigurer.processProperties(PropertySourcesPlaceholderConfigurer.java:182) ~[spring-context-5.2.5.RELEASE.
jar:5.2.5.RELEASE]
shopizer       |        at org.springframework.context.support.PropertySourcesPlaceholderConfigurer.postProcessBeanFactory(PropertySourcesPlaceholderConfigurer.java:157) ~[spring-context-5.2.5.REL
EASE.jar:5.2.5.RELEASE]
shopizer       |        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:286) ~[spring-context-5.2.5.
RELEASE.jar:5.2.5.RELEASE]
shopizer       |        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:166) ~[spring-context-5.2.5.
RELEASE.jar:5.2.5.RELEASE]
shopizer       |        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:706) ~[spring-context-5.2.5.RELEASE.jar:5.
2.5.RELEASE]
shopizer       |        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532) ~[spring-context-5.2.5.RELEASE.jar:5.2.5.RELEASE]
shopizer       |        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.6.RELEASE.jar:2.2.
6.RELEASE]
shopizer       |        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
shopizer       |        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
shopizer       |        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
shopizer       |        at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:152) [spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
shopizer       |        at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:132) [spring-boot-2.2.6.RELEASE.
jar:2.2.6.RELEASE]
shopizer       |        at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:92) [spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
shopizer       |        at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:172) [spring-web-5.2.5.RELEASE.jar:5.2.5.RELEASE]
shopizer       |        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5225) [catalina.jar:8.5.40]
shopizer       |        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:8.5.40]
shopizer       |        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754) [catalina.jar:8.5.40]
shopizer       |        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730) [catalina.jar:8.5.40]
shopizer       |        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734) [catalina.jar:8.5.40]

**Comment by basha-druvstar** [comment]
Has anybody found a solution to this problem?

**Comment by shopizer-ecommerce** [comment]
Do you have a configuration similar to this ?

https://github.com/shopizer-ecommerce/shopizer-docker-compose/blob/master/docker-compose-aws.yml

**Comment by xie-shujian** [comment]
how can i disabled it
