### ISSUE TITLE
Unable to view categories added , as a Store Admin (Not Shopizer Admin)

### ISSUE THREAD

**Issue by deceivingrakesh** [shopizer-ecommerce/shopizer#467]
When a store admin tries to view categories or do anything with it , it's failing with following log
http://localhost:8080/admin/categories/editCategory.html?id=100

java.lang.NullPointerException at com.salesmanager.core.business.services.catalog.category.CategoryServiceImpl.getById(CategoryServiceImpl.java:182) at com.salesmanager.core.business.services.catalog.category.CategoryServiceImpl$$FastClassBySpringCGLIB$$6f9b42cd.invoke(<generated>) at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366) at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175) at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) at com.salesmanager.core.business.services.catalog.category.CategoryServiceImpl$$EnhancerBySpringCGLIB$$867c2e21.getById(<generated>) at com.salesmanager.shop.admin.controller.categories.CategoryController.displayCategory(CategoryController.java:80) at com.salesmanager.shop.admin.controller.categories.CategoryController.displayCategoryEdit(CategoryController.java:60) at com.salesmanager.shop.admin.controller.categories.CategoryController$$FastClassBySpringCGLIB$$c7a785d1.invoke(<generated>) at

**Comment by deceivingrakesh** [comment]
Wrongly reported
