### ISSUE TITLE
It can't be compiled (mvn generate-sources) under jdk8

### ISSUE THREAD

**Issue by colinger** [shopizer-ecommerce/shopizer#48]
Caused by: javax.lang.model.type.UnknownTypeException: Unknown type: java.lang.Object&java.io.Serializable&java.lang.Comparable<K>
	at javax.lang.model.util.AbstractTypeVisitor6.visitUnknown(AbstractTypeVisitor6.java:150)
	at javax.lang.model.util.AbstractTypeVisitor6.visitIntersection(AbstractTypeVisitor6.java:133)
	at com.sun.tools.javac.code.Type$IntersectionClassType.accept(Type.java:1019)
	at javax.lang.model.util.AbstractTypeVisitor6.visit(AbstractTypeVisitor6.java:92)
	at com.mysema.query.apt.ExtendedTypeFactory$2.visitTypeVariable(ExtendedTypeFactory.java:250)
	at com.mysema.query.apt.ExtendedTypeFactory$2.visitTypeVariable(ExtendedTypeFactory.java:199)
	at com.sun.tools.javac.code.Type$TypeVar.accept(Type.java:1319)
	at javax.lang.model.util.AbstractTypeVisitor6.visit(AbstractTypeVisitor6.java:92)
	at com.mysema.query.apt.ExtendedTypeFactory$2.visitDeclared(ExtendedTypeFactory.java:233)
	at com.mysema.query.apt.ExtendedTypeFactory$2.visitDeclared(ExtendedTypeFactory.java:199)
	at com.sun.tools.javac.code.Type$ClassType.accept(Type.java:936)
	at javax.lang.model.util.AbstractTypeVisitor6.visit(AbstractTypeVisitor6.java:92)
	at com.mysema.query.apt.ExtendedTypeFactory.getEntityType(ExtendedTypeFactory.java:461)
	at com.mysema.query.apt.AbstractQuerydslProcessor.processAnnotations(AbstractQuerydslProcessor.java:114)
	at com.mysema.query.apt.AbstractQuerydslProcessor.process(AbstractQuerydslProcessor.java:97)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
	... 24 more

**Comment by yuzhiping** [comment]
I have the same problem (jdk installed in my computer also is jdk1.8).did you solve it?

**Comment by shopizer-ecommerce** [comment]
Yes all of this is because of JDK 1.8, please use 1.7

**Comment by FibreFoX** [comment]
http://www.oracle.com/technetwork/java/eol-135779.html#Java6-end-public-updates
> After April 2015, Oracle will no longer post updates of Java SE 7 to its public download sites. Existing Java SE 7 downloads already posted as of April 2015 will remain accessible in the Java Archive on Oracle Technology Network. Developers and end-users are encouraged to update to more recent Java SE versions that remain available for public download.

Please consider of upgrading, JDK 1.7 is more then deprecated and without update-support

**Comment by umeshawasthi** [comment]
This has been fixed with 2.0.3, please test with 2.0.3
