### ISSUE TITLE
Getting some  error on run command: mvn clean install

### ISSUE THREAD

**Issue by mohiddinbasha** [shopizer-ecommerce/shopizer#481]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 175.758 s - in com.salesmanager.test.catalog.CategoryTest
[INFO] Running com.salesmanager.test.catalog.ManufacturerTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.63 s - in com.salesmanager.test.catalog.ManufacturerTest
[INFO] Running com.salesmanager.test.catalog.ProductNextGenTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.995 s - in com.salesmanager.test.catalog.ProductNextGenTest
[INFO] Running com.salesmanager.test.catalog.ProductTest
Total number of items 4
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.501 s <<< FAILURE! - in com.salesmanager.test.catalog.ProductTest
[ERROR] testCreateProduct  Time elapsed: 2.466 s  <<< FAILURE!
java.lang.AssertionError: expected:<6> but was:<3>
	at com.salesmanager.test.catalog.ProductTest.testAttributes(ProductTest.java:516)
	at com.salesmanager.test.catalog.ProductTest.testCreateProduct(ProductTest.java:338)

[INFO] Running com.salesmanager.test.common.AbstractSalesManagerCoreTestCase
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.001 s - in com.salesmanager.test.common.AbstractSalesManagerCoreTestCase
[INFO] Running com.salesmanager.test.content.ContentFolderTest
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0 s - in com.salesmanager.test.content.ContentFolderTest
[INFO] Running com.salesmanager.test.content.ContentImagesTest
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.002 s - in com.salesmanager.test.content.ContentImagesTest
[INFO] Running com.salesmanager.test.content.StaticContentTest
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.001 s - in com.salesmanager.test.content.StaticContentTest
[INFO] Running com.salesmanager.test.customer.CustomerTest
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.001 s - in com.salesmanager.test.customer.CustomerTest
[INFO] Running com.salesmanager.test.order.InvoiceTest
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.001 s - in com.salesmanager.test.order.InvoiceTest
[INFO] Running com.salesmanager.test.order.OrderTest
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0 s - in com.salesmanager.test.order.OrderTest
[INFO] Running com.salesmanager.test.references.ReferencesTest
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0 s - in com.salesmanager.test.references.ReferencesTest
[INFO] Running JUnit Vintage
2020-09-30 21:45:57.816 ERROR 116240 --- [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : Unique index or primary key violation: "SALESMANAGER.UKS8OFSN9PEHDRSTJG52J5QABXH_INDEX_1 ON SALESMANAGER.PRODUCT(MERCHANT_ID, SKU) VALUES ( /* key:2 */ 3, TIMESTAMP '2020-09-30 21:45:57.788', TIMESTAMP '2020-09-30 21:45:57.788', NULL, TRUE, NULL, TIMESTAMP '2020-09-30 21:45:57.784', FALSE, 4.00, FALSE, 3.00, NULL, NULL, NULL, FALSE, FALSE, NULL, 1.00, NULL, NULL, NULL, NULL, 'TB12345', 0, 9, 1, NULL, NULL, NULL)"; SQL statement:
insert into SALESMANAGER.PRODUCT (DATE_CREATED, DATE_MODIFIED, UPDT_ID, AVAILABLE, COND, DATE_AVAILABLE, MANUFACTURER_ID, MERCHANT_ID, CUSTOMER_ID, PREORDER, PRODUCT_HEIGHT, PRODUCT_FREE, PRODUCT_LENGTH, QUANTITY_ORDERED, REVIEW_AVG, REVIEW_COUNT, PRODUCT_SHIP, PRODUCT_VIRTUAL, PRODUCT_WEIGHT, PRODUCT_WIDTH, REF_SKU, RENTAL_DURATION, RENTAL_PERIOD, RENTAL_STATUS, SKU, SORT_ORDER, TAX_CLASS_ID, PRODUCT_TYPE_ID, PRODUCT_ID) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-200]
[ERROR] Tests run: 6, Failures: 0, Errors: 1, Skipped: 5, Time elapsed: 0.023 s <<< FAILURE! - in JUnit Vintage
[ERROR] createShoppingCart  Time elapsed: 0.001 s  <<< ERROR!
org.springframework.dao.DataIntegrityViolationException: 
could not execute statement; SQL [n/a]; constraint ["SALESMANAGER.UKS8OFSN9PEHDRSTJG52J5QABXH_INDEX_1 ON SALESMANAGER.PRODUCT(MERCHANT_ID, SKU) VALUES ( /* key:2 */ 3, TIMESTAMP '2020-09-30 21:45:57.788', TIMESTAMP '2020-09-30 21:45:57.788', NULL, TRUE, NULL, TIMESTAMP '2020-09-30 21:45:57.784', FALSE, 4.00, FALSE, 3.00, NULL, NULL, NULL, FALSE, FALSE, NULL, 1.00, NULL, NULL, NULL, NULL, 'TB12345', 0, 9, 1, NULL, NULL, NULL)"; SQL statement:
insert into SALESMANAGER.PRODUCT (DATE_CREATED, DATE_MODIFIED, UPDT_ID, AVAILABLE, COND, DATE_AVAILABLE, MANUFACTURER_ID, MERCHANT_ID, CUSTOMER_ID, PREORDER, PRODUCT_HEIGHT, PRODUCT_FREE, PRODUCT_LENGTH, QUANTITY_ORDERED, REVIEW_AVG, REVIEW_COUNT, PRODUCT_SHIP, PRODUCT_VIRTUAL, PRODUCT_WEIGHT, PRODUCT_WIDTH, REF_SKU, RENTAL_DURATION, RENTAL_PERIOD, RENTAL_STATUS, SKU, SORT_ORDER, TAX_CLASS_ID, PRODUCT_TYPE_ID, PRODUCT_ID) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-200]]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
	at com.salesmanager.test.shoppingcart.ShoppingCartTest.createShoppingCart(ShoppingCartTest.java:219)
Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement
	at com.salesmanager.test.shoppingcart.ShoppingCartTest.createShoppingCart(ShoppingCartTest.java:219)
Caused by: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: 
Unique index or primary key violation: "SALESMANAGER.UKS8OFSN9PEHDRSTJG52J5QABXH_INDEX_1 ON SALESMANAGER.PRODUCT(MERCHANT_ID, SKU) VALUES ( /* key:2 */ 3, TIMESTAMP '2020-09-30 21:45:57.788', TIMESTAMP '2020-09-30 21:45:57.788', NULL, TRUE, NULL, TIMESTAMP '2020-09-30 21:45:57.784', FALSE, 4.00, FALSE, 3.00, NULL, NULL, NULL, FALSE, FALSE, NULL, 1.00, NULL, NULL, NULL, NULL, 'TB12345', 0, 9, 1, NULL, NULL, NULL)"; SQL statement:
insert into SALESMANAGER.PRODUCT (DATE_CREATED, DATE_MODIFIED, UPDT_ID, AVAILABLE, COND, DATE_AVAILABLE, MANUFACTURER_ID, MERCHANT_ID, CUSTOMER_ID, PREORDER, PRODUCT_HEIGHT, PRODUCT_FREE, PRODUCT_LENGTH, QUANTITY_ORDERED, REVIEW_AVG, REVIEW_COUNT, PRODUCT_SHIP, PRODUCT_VIRTUAL, PRODUCT_WEIGHT, PRODUCT_WIDTH, REF_SKU, RENTAL_DURATION, RENTAL_PERIOD, RENTAL_STATUS, SKU, SORT_ORDER, TAX_CLASS_ID, PRODUCT_TYPE_ID, PRODUCT_ID) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-200]
	at com.salesmanager.test.shoppingcart.ShoppingCartTest.createShoppingCart(ShoppingCartTest.java:219)

2020-09-30 21:45:58.655  INFO 116240 --- [extShutdownHook] o.s.c.ehcache.EhCacheManagerFactoryBean  : Shutting down EhCache CacheManager
2020-09-30 21:46:00.650  INFO 116240 --- [extShutdownHook] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2020-09-30 21:46:00.824  INFO 116240 --- [extShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2020-09-30 21:46:00.913  INFO 116240 --- [extShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ProductTest.testCreateProduct:338->testAttributes:516 expected:<6> but was:<3>
[ERROR] Errors: 
[ERROR]   ShoppingCartTest.createShoppingCart:219 » DataIntegrityViolation could not exe...
[INFO] 
[ERROR] Tests run: 18, Failures: 1, Errors: 1, Skipped: 13
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for shopizer 2.13.0:
[INFO] 
[INFO] shopizer ........................................... SUCCESS [  6.147 s]
[INFO] sm-core-model ...................................... SUCCESS [ 47.009 s]
[INFO] sm-core-modules .................................... SUCCESS [  3.590 s]
[INFO] sm-core ............................................ FAILURE [03:55 min]
[INFO] sm-shop-model ...................................... SKIPPED
[INFO] sm-shop ............................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:56 min
[INFO] Finished at: 2020-09-30T21:46:02+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project sm-core: There are test failures.
[ERROR] 
[ERROR] Please refer to C:\mohi2018n2019\springssuitewrkspace10\shopizer-master\sm-core\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :sm-core

**Comment by emerson-matos** [comment]
@mohiddinbasha Could you improve this issue content? [You can check here for more information on how to do it](https://opensource.guide/how-to-contribute/#what-happens-after-you-submit-a-contribution)
