### ISSUE TITLE
Not able to start the application

### ISSUE THREAD

**Issue by chandresh-pancholi** [shopizer-ecommerce/shopizer#517]
````
Caused by: java.lang.IllegalArgumentException: No URL for ServletContext resource [/WEB-INF/tiles/tiles-admin.xml]
	at org.springframework.web.servlet.view.tiles3.SpringWildcardServletTilesApplicationContext.getResources(SpringWildcardServletTilesApplicationContext.java:100) ~[spring-webmvc-5.2.11.RELEASE.jar:5.2.11.RELEASE]
	at org.springframework.web.servlet.view.tiles3.TilesConfigurer$SpringTilesContainerFactory.getSources(TilesConfigurer.java:316) ~[spring-webmvc-5.2.11.RELEASE.jar:5.2.11.RELEASE]
	at org.apache.tiles.factory.BasicTilesContainerFactory.createLocaleDefinitionDao(BasicTilesContainerFactory.java:182) ~[tiles-core-3.0.4.jar:3.0.4]
	at org.apache.tiles.factory.BasicTilesContainerFactory.createDefinitionsFactory(BasicTilesContainerFactory.java:137) ~[tiles-core-3.0.4.jar:3.0.4]
	at org.springframework.web.servlet.view.tiles3.TilesConfigurer$SpringTilesContainerFactory.createDefinitionsFactory(TilesConfigurer.java:364) ~[spring-webmvc-5.2.11.RELEASE.jar:5.2.11.RELEASE]
	at org.apache.tiles.factory.BasicTilesContainerFactory.createContainer(BasicTilesContainerFactory.java:86) ~[tiles-core-3.0.4.jar:3.0.4]
	at org.apache.tiles.startup.AbstractTilesInitializer.createContainer(AbstractTilesInitializer.java:114) ~[tiles-core-3.0.4.jar:3.0.4]
	at org.apache.tiles.startup.AbstractTilesInitializer.initialize(AbstractTilesInitializer.java:64) ~[tiles-core-3.0.4.jar:3.0.4]
	at org.springframework.web.servlet.view.tiles3.TilesConfigurer.afterPropertiesSet(TilesConfigurer.java:280) ~[spring-webmvc-5.2.11.RELEASE.jar:5.2.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1853) ~[spring-beans-5.2.11.RELEASE.jar:5.2.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1790) ~[spring-beans-5.2.11.RELEASE.jar:5.2.11.RELEASE]
	... 17 common frames omitted
Caused by: java.io.FileNotFoundException: ServletContext resource [/WEB-INF/tiles/tiles-admin.xml] cannot be resolved to URL because it does not exist
	at org.springframework.web.context.support.ServletContextResource.getURL(ServletContextResource.java:174) ~[spring-web-5.2.11.RELEASE.jar:5.2.11.RELEASE]
	at org.springframework.web.servlet.view.tiles3.SpringWildcardServletTilesApplicationContext.getResources(SpringWildcardServletTilesApplicationContext.java:95) ~[spring-webmvc-5.2.11.RELEASE.jar:5.2.11.RELEASE]
	... 27 common frames omitted
```

**Comment by marcosechague** [comment]
If you use IntelliJ, please refer to this:
https://github.com/shopizer-ecommerce/shopizer/issues/526
