### ISSUE TITLE
Could not commit JPA transaction

### ISSUE THREAD

**Issue by AtorVdm** [shopizer-ecommerce/shopizer#69]
Hi, I have a problem with shopizer.
After adding the product or category in admin panel, when we want to browse the generated url for the product or category we face this exception. 
[Apache Tomcat_8.0.pdf](https://github.com/shopizer-ecommerce/shopizer/files/169220/Apache.Tomcat_8.0.pdf)
After adding the category it appears on the main page of the website, but after navigating to it we get the same exception. What could cause this problem?

**Comment by umeshawasthi** [comment]
@AtorVdm 
I followed these steps and not able to replicate this issue.
I added a new product and able to navigate to PDP, I also added new category and assigned product to category and able to navigate to PDP and search result page.

**Comment by wouterla** [comment]
I'm seeing the same error, with a freshly checked out 2.0.3 branch, test-data generated and the h2 db. And then just click on the 'computer books' category from the main page.

It seems that the query that is generated does an order by for a field that's not selected, and this can give problems:

[h2 error code documentation](http://www.h2database.com/javadoc/org/h2/api/ErrorCode.html#c90068)

`
DEBUG com.mchange.v2.c3p0.impl.NewPooledConnection: com.mchange.v2.c3p0.impl.NewPooledConnection@570b271a handling a throwable.
org.h2.jdbc.JdbcSQLException: Order by expression "LANGUAGE3_.LANGUAGE_ID" must be in the result list in this case; SQL statement:
select distinct category0_.CATEGORY_ID as CATEGORY1_165_0_, descriptio1_.DESCRIPTION_ID as DESCRIPT1_166_1_, merchantst2_.MERCHANT_ID as MERCHANT1_133_2_, category0_.DATE_CREATED as DATE2_165_0_, category0_.DATE_MODIFIED as DATE3_165_0_, category0_.UPDT_ID as UPDT4_165_0_, category0_.CATEGORY_IMAGE as CATEGORY5_165_0_, category0_.CATEGORY_STATUS as CATEGORY6_165_0_, category0_.CODE as CODE165_0_, category0_.DEPTH as DEPTH165_0_, category0_.LINEAGE as LINEAGE165_0_, category0_.MERCHANT_ID as MERCHANT12_165_0_, category0_.PARENT_ID as PARENT13_165_0_, category0_.SORT_ORDER as SORT10_165_0_, category0_.VISIBLE as VISIBLE165_0_, descriptio1_.DATE_CREATED as DATE2_166_1_, descriptio1_.DATE_MODIFIED as DATE3_166_1_, descriptio1_.UPDT_ID as UPDT4_166_1_, descriptio1_.DESCRIPTION as DESCRIPT5_166_1_, descriptio1_.LANGUAGE_ID as LANGUAGE13_166_1_, descriptio1_.NAME as NAME166_1_, descriptio1_.TITLE as TITLE166_1_, descriptio1_.CATEGORY_ID as CATEGORY14_166_1_, descriptio1_.CATEGORY_HIGHLIGHT as CATEGORY8_166_1_, descriptio1_.META_DESCRIPTION as META9_166_1_, descriptio1_.META_KEYWORDS as META10_166_1_, descriptio1_.META_TITLE as META11_166_1_, descriptio1_.SEF_URL as SEF12_166_1_, descriptio1_.CATEGORY_ID as CATEGORY14_165_0__, descriptio1_.DESCRIPTION_ID as DESCRIPT1_0__, merchantst2_.STORE_CODE as STORE2_133_2_, merchantst2_.CONTINUESHOPPINGURL as CONTINUE3_133_2_, merchantst2_.COUNTRY_ID as COUNTRY20_133_2_, merchantst2_.CURRENCY_ID as CURRENCY21_133_2_, merchantst2_.CURRENCY_FORMAT_NATIONAL as CURRENCY4_133_2_, merchantst2_.LANGUAGE_ID as LANGUAGE22_133_2_, merchantst2_.DOMAIN_NAME as DOMAIN5_133_2_, merchantst2_.IN_BUSINESS_SINCE as IN6_133_2_, merchantst2_.INVOICE_TEMPLATE as INVOICE7_133_2_, merchantst2_.SEIZEUNITCODE as SEIZEUNI8_133_2_, merchantst2_.STORE_EMAIL as STORE9_133_2_, merchantst2_.STORE_LOGO as STORE10_133_2_, merchantst2_.STORE_TEMPLATE as STORE11_133_2_, merchantst2_.STORE_ADDRESS as STORE12_133_2_, merchantst2_.STORE_CITY as STORE13_133_2_, merchantst2_.STORE_NAME as STORE14_133_2_, merchantst2_.STORE_PHONE as STORE15_133_2_, merchantst2_.STORE_POSTAL_CODE as STORE16_133_2_, merchantst2_.STORE_STATE_PROV as STORE17_133_2_, merchantst2_.USE_CACHE as USE18_133_2_, merchantst2_.WEIGHTUNITCODE as WEIGHTU19_133_2_, merchantst2_.ZONE_ID as ZONE23_133_2_ from SALESMANAGER.CATEGORY category0_ left outer join SALESMANAGER.CATEGORY_DESCRIPTION descriptio1_ on category0_.CATEGORY_ID=descriptio1_.CATEGORY_ID left outer join SALESMANAGER.LANGUAGE language3_ on descriptio1_.LANGUAGE_ID=language3_.LANGUAGE_ID left outer join SALESMANAGER.MERCHANT_STORE merchantst2_ on category0_.MERCHANT_ID=merchantst2_.MERCHANT_ID where (category0_.LINEAGE like ? escape '!') and category0_.MERCHANT_ID=? order by category0_.SORT_ORDER asc, category0_.LINEAGE asc, category0_.LINEAGE asc, category0_.DEPTH asc, language3_.LANGUAGE_ID desc [90068-152]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:327)
	at org.h2.message.DbException.get(DbException.java:167)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.command.dml.Query.initOrder(Query.java:359)
	at org.h2.command.dml.Select.init(Select.java:695)
	at org.h2.command.Parser.parseSelect(Parser.java:1470)
	at org.h2.command.Parser.parsePrepared(Parser.java:401)
	at org.h2.command.Parser.parse(Parser.java:275)
	at org.h2.command.Parser.parse(Parser.java:247)
	at org.h2.command.Parser.prepare(Parser.java:201)
	at org.h2.command.Parser.prepareCommand(Parser.java:214)
	at org.h2.engine.Session.prepareLocal(Session.java:426)
	at org.h2.engine.Session.prepareCommand(Session.java:374)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1093)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:71)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:243)
	at com.mchange.v2.c3p0.impl.NewProxyConnection.prepareStatement(NewProxyConnection.java:213)
	at sun.reflect.GeneratedMethodAccessor85.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.hibernate.engine.jdbc.internal.proxy.ConnectionProxyHandler.continueInvocation(ConnectionProxyHandler.java:138)
	at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)
	at com.sun.proxy.$Proxy170.prepareStatement(Unknown Source)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:147)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:166)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:145)
	at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1720)
	at org.hibernate.loader.Loader.doQuery(Loader.java:828)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:289)
	at org.hibernate.loader.Loader.doList(Loader.java:2447)
	at org.hibernate.loader.Loader.doList(Loader.java:2433)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2263)
	at org.hibernate.loader.Loader.list(Loader.java:2258)
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:470)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:355)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:195)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1215)
	at org.hibernate.internal.QueryImpl.list(QueryImpl.java:101)
	at org.hibernate.ejb.QueryImpl.getResultList(QueryImpl.java:256)
	at com.mysema.query.jpa.impl.AbstractJPAQuery.getResultList(AbstractJPAQuery.java:195)
	at com.mysema.query.jpa.impl.AbstractJPAQuery.list(AbstractJPAQuery.java:243)
	at com.salesmanager.core.business.catalog.category.dao.CategoryDaoImpl.listByLineage(CategoryDaoImpl.java:200)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:155)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	at com.sun.proxy.$Proxy71.listByLineage(Unknown Source)
	at com.salesmanager.core.business.catalog.category.service.CategoryServiceImpl.listByLineage(CategoryServiceImpl.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:96)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:260)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:94)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:161)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:91)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:204)
	at com.sun.proxy.$Proxy75.listByLineage(Unknown Source)
	at com.salesmanager.web.shop.controller.category.ShoppingCategoryController.displayCategory(ShoppingCategoryController.java:178)
	at com.salesmanager.web.shop.controller.category.ShoppingCategoryController.displayCategoryWithReference(ShoppingCategoryController.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:215)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:743)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:672)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:82)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:933)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:867)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:951)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:842)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:827)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:835)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1685)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:118)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:84)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:103)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:113)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:154)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:45)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:150)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.ui.DefaultLoginPageGeneratingFilter.doFilter(DefaultLoginPageGeneratingFilter.java:155)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:199)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:110)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:50)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:106)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:342)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:192)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:160)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:343)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:260)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:106)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
DEBUG com.mchange.v2.sql.SqlUtils: Attempted to convert SQLException to SQLException. Leaving it alone. [SQLState: 90068; errorCode: 90068]
`

**Comment by wouterla** [comment]
If I remove the description language from all the order-by's in the CategoryDaoImpl, I get rid of all the errors. 

The 'TODO add language' comment seems to indicate that this might be a known issue? Or maybe MySQL simply doesn't care about this while h2 does?

**Comment by shopizer-ecommerce** [comment]
That happens for some of the uses in H2. The easiest way is to use MySQL instead

**Comment by shopizer-ecommerce** [comment]
Outated issue, closing it
